import { Tool } from './types';

export const initialTools: Tool[] = [
  {
    id: 'tool-0',
    name: 'Minimax Agent',
    description: 'منصة وكلاء ذكاء اصطناعي متقدمة.',
    category: 'وكلاء',
    toolUrl: 'https://agent.minimax.io/',
    imageUrl: 'https://picsum.photos/seed/Minimax Agent/500/300',
    featured: false,
  },
  {
    id: 'tool-1',
    name: 'Emily AI',
    description: 'وكيلة AI متخصصة في المبيعات ودعم العملاء.',
    category: 'وكلاء',
    toolUrl: 'https://www.emily.ai/',
    imageUrl: 'https://picsum.photos/seed/Emily AI/500/300',
    featured: false,
  },
  {
    id: 'tool-2',
    name: 'RunComfy',
    description: 'واجهة رسومية لتشغيل نماذج Stable Diffusion.',
    category: 'ميديا',
    toolUrl: 'http://www.runcomfy.com',
    imageUrl: 'https://picsum.photos/seed/RunComfy/500/300',
    featured: true,
  },
  {
    id: 'tool-3',
    name: 'Blink',
    description: 'لإنشاء تطبيقات الويب والموبايل كاملة بالذكاء الاصطناعي.',
    category: 'vibe coding',
    toolUrl: 'https://blink.new/',
    imageUrl: 'https://picsum.photos/seed/Blink/500/300',
    featured: false,
  },
  {
    id: 'tool-4',
    name: 'Weavy',
    description: 'منصة لتوليد الميديا بالذكاء الاصطناعي عبر ComfyUI Cloud.',
    category: 'ميديا',
    toolUrl: 'https://app.weavy.ai/',
    imageUrl: 'https://picsum.photos/seed/Weavy/500/300',
    featured: false,
  },
  {
    id: 'tool-5',
    name: 'وركفلو Qwen السينمائي',
    description: 'لتعديل الصور وعمل ستوريبورد ولقطات سينمائية باستخدام نموذج Qwen.',
    category: 'ميديا',
    toolUrl: 'https://www.runninghub.ai/ai-detail/1978885072088633345',
    imageUrl: 'https://picsum.photos/seed/وركفلو Qwen السينمائي/500/300',
    featured: false,
  },
  {
    id: 'tool-6',
    name: 'Serper API',
    description: 'يوفر API مجاني لنتائج بحث جوجل.',
    category: 'vibe coding',
    toolUrl: 'https://serper.dev/dashboard',
    imageUrl: 'https://picsum.photos/seed/Serper API/500/300',
    featured: false,
  },
  {
    id: 'tool-7',
    name: 'LM Arena',
    description: 'منصة مقارنة وتوليد للميديا بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://lmarena.ai/',
    imageUrl: 'https://picsum.photos/seed/LM Arena/500/300',
    featured: false,
  },
  {
    id: 'tool-8',
    name: 'Envato Elements',
    description: 'مكتبة ضخمة من الأصول الإبداعية والجاهزة للاستخدام.',
    category: 'ميديا',
    toolUrl: 'https://elements.envato.com',
    imageUrl: 'https://picsum.photos/seed/Envato Elements/500/300',
    featured: false,
  },
  {
    id: 'tool-9',
    name: 'Phot AI',
    description: 'محرر صور يعمل بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://phot.ai/',
    imageUrl: 'https://picsum.photos/seed/Phot AI/500/300',
    featured: false,
  },
  {
    id: 'tool-10',
    name: 'Hugging Face',
    description: 'منصة مجتمعية لبناء وتدريب ونشر نماذج تعلم الآلة.',
    category: 'منصات',
    toolUrl: 'https://huggingface.co/',
    imageUrl: 'https://picsum.photos/seed/Hugging Face/500/300',
    featured: true,
  },
  {
    id: 'tool-11',
    name: 'Z.AI Chat',
    description: 'وكيل ذكاء اصطناعي لبناء العروض التقديمية والمهام.',
    category: 'وكلاء',
    toolUrl: 'https://chat.z.ai/',
    imageUrl: 'https://picsum.photos/seed/Z.AI Chat/500/300',
    featured: false,
  },
  {
    id: 'tool-12',
    name: 'Google AI Studio',
    description: 'أداة من جوجل لبناء النماذج الأولية باستخدام Gemini.',
    category: 'منصات',
    toolUrl: 'https://aistudio.google.com',
    imageUrl: 'https://picsum.photos/seed/Google AI Studio/500/300',
    featured: true,
  },
  {
    id: 'tool-13',
    name: 'Perplexity',
    description: 'محرك بحث محادثة يقدم إجابات مباشرة مدعومة بالمصادر.',
    category: 'بحث',
    toolUrl: 'https://www.perplexity.ai/',
    imageUrl: 'https://picsum.photos/seed/Perplexity/500/300',
    featured: true,
  },
  {
    id: 'tool-14',
    name: 'Yupp',
    description: 'محرك بحث يعتمد على المحادثة للحصول على إجابات.',
    category: 'محادثة',
    toolUrl: 'https://yupp.ai/',
    imageUrl: 'https://picsum.photos/seed/Yupp/500/300',
    featured: false,
  },
  {
    id: 'tool-15',
    name: 'Claude',
    description: 'مساعد محادثة ذكي ومنافس قوي لـ ChatGPT.',
    category: 'محادثة',
    toolUrl: 'https://claude.ai/',
    imageUrl: 'https://picsum.photos/seed/Claude/500/300',
    featured: true,
  },
  {
    id: 'tool-16',
    name: 'Google Opal',
    description: 'مشاريع وأدوات تجريبية من جوجل في مجال الذكاء الاصطناعي.',
    category: 'منصات',
    toolUrl: 'https://opal.withgoogle.com',
    imageUrl: 'https://picsum.photos/seed/Google Opal/500/300',
    featured: false,
  },
  {
    id: 'tool-17',
    name: 'Expertex',
    description: 'منصة محادثة متخصصة لتقديم الخبرة الفورية.',
    category: 'محادثة',
    toolUrl: 'https://expertex.ai/',
    imageUrl: 'https://picsum.photos/seed/Expertex/500/300',
    featured: false,
  },
  {
    id: 'tool-18',
    name: 'Qwen Chat',
    description: 'نموذج محادثة قوي من تطوير Alibaba Cloud.',
    category: 'محادثة',
    toolUrl: 'https://chat.qwen.ai/',
    imageUrl: 'https://picsum.photos/seed/Qwen Chat/500/300',
    featured: false,
  },
  {
    id: 'tool-19',
    name: 'Skywork',
    description: 'وكيل ذكاء اصطناعي للمساعدة في المهام المتعددة.',
    category: 'وكلاء',
    toolUrl: 'https://skywork.ai',
    imageUrl: 'https://picsum.photos/seed/Skywork/500/300',
    featured: false,
  },
  {
    id: 'tool-20',
    name: 'DeepSeek Chat',
    description: 'نموذج دردشة متخصص في البرمجة والمهام التقنية.',
    category: 'محادثة',
    toolUrl: 'https://chat.deepseek.com/',
    imageUrl: 'https://picsum.photos/seed/DeepSeek Chat/500/300',
    featured: false,
  },
  {
    id: 'tool-21',
    name: 'Kimi Slides',
    description: 'يستطيع عمل شرائح عرض فني.',
    category: 'ميديا',
    toolUrl: 'https://www.kimi.com/kimiplus/slides',
    imageUrl: 'https://picsum.photos/seed/Kimi Slides/500/300',
    featured: false,
  },
  {
    id: 'tool-22',
    name: 'SEO Mega Report',
    description: 'أداة لتحليل وتقارير تحسين محركات البحث (SEO).',
    category: 'تسويق',
    toolUrl: 'https://seomegareport.com/',
    imageUrl: 'https://picsum.photos/seed/SEO Mega Report/500/300',
    featured: false,
  },
  {
    id: 'tool-23',
    name: 'WAN Video',
    description: 'منصة لإنشاء وتحرير مقاطع الفيديو بسهولة.',
    category: 'ميديا',
    toolUrl: 'https://create.wan.video/',
    imageUrl: 'https://picsum.photos/seed/WAN Video/500/300',
    featured: false,
  },
  {
    id: 'tool-24',
    name: 'Nanovate',
    description: 'منصة لإدارة المشاريع والأدوات التقنية المبتكرة.',
    category: 'منصات',
    toolUrl: 'https://dashboard.nanovate.io/',
    imageUrl: 'https://picsum.photos/seed/Nanovate/500/300',
    featured: false,
  },
  {
    id: 'tool-25',
    name: 'Ideogram',
    description: 'أداة لتوليد الصور الفنية والإبداعية من النصوص.',
    category: 'ميديا',
    toolUrl: 'https://ideogram.ai',
    imageUrl: 'https://picsum.photos/seed/Ideogram/500/300',
    featured: true,
  },
  {
    id: 'tool-26',
    name: 'Reve',
    description: 'منصة لتوليد الميديا بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://app.reve.com/home',
    imageUrl: 'https://picsum.photos/seed/Reve/500/300',
    featured: false,
  },
  {
    id: 'tool-27',
    name: 'Nordy',
    description: 'منصة لتوليد الميديا عبر ComfyUI Cloud workflows.',
    category: 'ميديا',
    toolUrl: 'https://nordy.ai/',
    imageUrl: 'https://picsum.photos/seed/Nordy/500/300',
    featured: false,
  },
  {
    id: 'tool-28',
    name: 'Tencent Hunyuan',
    description: 'منصة للنماذج اللغوية الكبيرة من تطوير شركة تنسنت.',
    category: 'منصات',
    toolUrl: 'https://hunyuan.tencent.com',
    imageUrl: 'https://picsum.photos/seed/Tencent Hunyuan/500/300',
    featured: false,
  },
  {
    id: 'tool-29',
    name: 'ImageFX',
    description: 'أداة من جوجل لتوليد وتعديل الصور بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://labs.google/fx/tools/image-fx/',
    imageUrl: 'https://picsum.photos/seed/ImageFX/500/300',
    featured: false,
  },
  {
    id: 'tool-30',
    name: 'LTX Studio',
    description: 'استوديو متكامل لإنشاء مقاطع الفيديو بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://app.ltx.studio/',
    imageUrl: 'https://picsum.photos/seed/LTX Studio/500/300',
    featured: false,
  },
  {
    id: 'tool-31',
    name: 'Whisk',
    description: 'مساعد ذكي من جوجل لتخطيط الوجبات والوصفات.',
    category: 'منصات',
    toolUrl: 'https://labs.google/fx/tools/whisk',
    imageUrl: 'https://picsum.photos/seed/Whisk/500/300',
    featured: false,
  },
  {
    id: 'tool-32',
    name: 'Sejda',
    description: 'محرر ملفات PDF مع ميزات ذكية متقدمة.',
    category: 'منصات',
    toolUrl: 'https://www.sejda.com/pdf-editor',
    imageUrl: 'https://picsum.photos/seed/Sejda/500/300',
    featured: false,
  },
  {
    id: 'tool-33',
    name: 'Sora',
    description: 'نموذج لتحويل النص إلى فيديو من OpenAI.',
    category: 'ميديا',
    toolUrl: 'https://sora.chatgpt.com/',
    imageUrl: 'https://picsum.photos/seed/Sora/500/300',
    featured: true,
  },
  {
    id: 'tool-34',
    name: 'Ebsynth',
    description: 'أداة لتحويل الرسومات واللوحات إلى رسوم متحركة.',
    category: 'ميديا',
    toolUrl: 'https://ebsynth.com/',
    imageUrl: 'https://picsum.photos/seed/Ebsynth/500/300',
    featured: false,
  },
  {
    id: 'tool-35',
    name: 'Golpo AI Video',
    description: 'منصة لإنشاء مقاطع فيديو من النصوص في دقائق.',
    category: 'ميديا',
    toolUrl: 'https://video.golpoai.com/',
    imageUrl: 'https://picsum.photos/seed/Golpo AI Video/500/300',
    featured: false,
  },
  {
    id: 'tool-36',
    name: 'مولد تعابير الوجه',
    description: 'تطبيق تفاعلي لتوليد وتعديل تعابير الوجه ووضعيات الجسم من صورة واحدة.',
    category: 'ميديا',
    toolUrl: 'https://aistudio.google.com/app/apps/drive/1r4kgvxm4VO9ZjQr02G-vJs4rbcig4ppJ?showPreview=true&showAssistant=true',
    imageUrl: 'https://picsum.photos/seed/مولد تعابير الوجه/500/300',
    featured: false,
  },
  {
    id: 'tool-37',
    name: 'Image Upscaler',
    description: 'رفع جودة الصورة مجانا.',
    category: 'ميديا',
    toolUrl: 'https://imgupscaler.ai/photo-enhancer/',
    imageUrl: 'https://picsum.photos/seed/Image Upscaler/500/300',
    featured: false,
  },
  {
    id: 'tool-38',
    name: 'AniEraser',
    description: 'أداة لإزالة العناصر غير المرغوب فيها من الصور والفيديو.',
    category: 'ميديا',
    toolUrl: 'https://anieraser.media.io/app/',
    imageUrl: 'https://picsum.photos/seed/AniEraser/500/300',
    featured: false,
  },
  {
    id: 'tool-39',
    name: 'RunningHub',
    description: 'منصة سحابية لـ ComfyUI لتوليد الميديا بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://www.runninghub.ai/',
    imageUrl: 'https://picsum.photos/seed/RunningHub/500/300',
    featured: false,
  },
  {
    id: 'tool-40',
    name: 'Baidu Yiyan',
    description: 'منصة صينية لتوليد الميديا بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://yiyan.baidu.com/',
    imageUrl: 'https://picsum.photos/seed/Baidu Yiyan/500/300',
    featured: false,
  },
  {
    id: 'tool-41',
    name: 'Sora Watermark Remover',
    description: 'أداة لإزالة العلامة المائية من فيديوهات Sora.',
    category: 'ميديا',
    toolUrl: 'https://www.topyappers.com/tools/sora-watermark-remover',
    imageUrl: 'https://picsum.photos/seed/Sora Watermark Remover/500/300',
    featured: false,
  },
  {
    id: 'tool-42',
    name: 'Minimax Audio',
    description: 'منصة متقدمة لاستنساخ وتحويل الصوت.',
    category: 'صوت',
    toolUrl: 'https://www.minimax.com/',
    imageUrl: 'https://picsum.photos/seed/Minimax Audio/500/300',
    featured: false,
  },
  {
    id: 'tool-43',
    name: 'Fish Audio',
    description: 'أداة لاستنساخ الصوت بجودة عالية للمبدعين.',
    category: 'صوت',
    toolUrl: 'https://fish.audio/',
    imageUrl: 'https://picsum.photos/seed/Fish Audio/500/300',
    featured: false,
  },
  {
    id: 'tool-44',
    name: 'ElevenLabs',
    description: 'رائد في توليد الكلام الواقعي واستنساخ الصوت.',
    category: 'صوت',
    toolUrl: 'https://elevenlabs.io/',
    imageUrl: 'https://picsum.photos/seed/ElevenLabs/500/300',
    featured: true,
  },
  {
    id: 'tool-45',
    name: 'Voice AI',
    description: 'مغير ومستنسخ صوتي فوري للألعاب والبث.',
    category: 'صوت',
    toolUrl: 'https://voice.ai/',
    imageUrl: 'https://picsum.photos/seed/Voice AI/500/300',
    featured: false,
  },
  {
    id: 'tool-46',
    name: 'Kits AI',
    description: 'مكتبة أصوات ومنصة استنساخ صوتي للموسيقيين.',
    category: 'صوت',
    toolUrl: 'https://www.kits.ai/',
    imageUrl: 'https://picsum.photos/seed/Kits AI/500/300',
    featured: false,
  },
  {
    id: 'tool-47',
    name: 'Vocloner',
    description: 'استنساخ الأصوات مع 1000 حرف مجاني يوميًا.',
    category: 'صوت',
    toolUrl: 'https://vocloner.com/',
    imageUrl: 'https://picsum.photos/seed/Vocloner/500/300',
    featured: false,
  },
  {
    id: 'tool-48',
    name: 'MMAudio',
    description: 'يعمل موسيقى للفيديو بالذكاء الاصطناعي.',
    category: 'صوت',
    toolUrl: 'https://huggingface.co/spaces/hkchengrex/MMAudio',
    imageUrl: 'https://picsum.photos/seed/MMAudio/500/300',
    featured: false,
  },
  {
    id: 'tool-49',
    name: 'Flow (WhisperFlow)',
    description: 'منصة لتحويل الصوت إلى نص (نسخ صوتي).',
    category: 'صوت',
    toolUrl: 'https://whspr.ai/',
    imageUrl: 'https://picsum.photos/seed/Flow (WhisperFlow)/500/300',
    featured: false,
  },
  {
    id: 'tool-50',
    name: 'Genspark',
    description: 'وكيل ذكاء اصطناعي لتوليد الأفكار والبحث.',
    category: 'وكلاء',
    toolUrl: 'https://www.genspark.ai/',
    imageUrl: 'https://picsum.photos/seed/Genspark/500/300',
    featured: false,
  },
  {
    id: 'tool-51',
    name: 'Sheetsy',
    description: 'منصة لإرسال وتخصيص الإيميلات بالذكاء الاصطناعي مباشرة من جداول البيانات.',
    category: 'تسويق',
    toolUrl: 'https://sheetsy.co',
    imageUrl: 'https://picsum.photos/seed/Sheetsy/500/300',
    featured: false,
  },
  {
    id: 'tool-52',
    name: 'Hera Motion',
    description: 'منصة لتحريك التصاميم والشعارات (اللوجوهات) بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://app.hera.video/motions',
    imageUrl: 'https://picsum.photos/seed/Hera Motion/500/300',
    featured: false,
  },
  {
    id: 'tool-53',
    name: 'Lovart AI',
    description: 'منصة لتوليد الصور والميديا الفنية بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://www.lovart.ai/',
    imageUrl: 'https://picsum.photos/seed/Lovart AI/500/300',
    featured: false,
  },
  {
    id: 'tool-54',
    name: 'مولد بطاقات الجامعات',
    description: 'أداة لإنشاء وميديا بطاقات هوية جامعية (ID).',
    category: 'ميديا',
    toolUrl: 'https://eduid.pages.dev/',
    imageUrl: 'https://picsum.photos/seed/مولد بطاقات الجامعات/500/300',
    featured: false,
  },
  {
    id: 'tool-55',
    name: 'CareerFlow',
    description: 'أداة لجمع بيانات العملاء المحتملين (leads) من لينكدإن.',
    category: 'تسويق',
    toolUrl: 'https://www.careerflow.ai/',
    imageUrl: 'https://picsum.photos/seed/CareerFlow/500/300',
    featured: false,
  },
  {
    id: 'tool-56',
    name: 'FSMVID',
    description: 'يقوم بتنزيل الميديا من منصات التواصل الاجتماعي.',
    category: 'تسويق',
    toolUrl: 'https://fsmvid.com/',
    imageUrl: 'https://picsum.photos/seed/FSMVID/500/300',
    featured: false,
  },
  {
    id: 'tool-57',
    name: 'Squidlr',
    description: 'أداة لتنزيل الفيديوهات والميديا من منصات التواصل الاجتماعي.',
    category: 'تسويق',
    toolUrl: 'https://www.squidlr.com/',
    imageUrl: 'https://picsum.photos/seed/Squidlr/500/300',
    featured: false,
  },
  {
    id: 'tool-58',
    name: 'BuiltWith',
    description: 'لمعرفة التقنيات والأنظمة التي بني بها أي موقع.',
    category: 'تسويق',
    toolUrl: 'https://builtwith.com/',
    imageUrl: 'https://picsum.photos/seed/BuiltWith/500/300',
    featured: false,
  },
  {
    id: 'tool-59',
    name: 'Wappalyzer',
    description: 'يكشف عن التقنيات المستخدمة في أي موقع، بديل لـ BuiltWith.',
    category: 'تسويق',
    toolUrl: 'https://www.wappalyzer.com/lookup/',
    imageUrl: 'https://picsum.photos/seed/Wappalyzer/500/300',
    featured: false,
  },
  {
    id: 'tool-60',
    name: 'AICarma',
    description: 'منصة لتحسين محركات الذكاء الاصطناعي (AIO) للبراندات، تجربة 14 يوم مجانية.',
    category: 'تسويق',
    toolUrl: 'https://aicarma.com',
    imageUrl: 'https://picsum.photos/seed/AICarma/500/300',
    featured: false,
  },
  {
    id: 'tool-61',
    name: 'Ubersuggest',
    description: 'دليل ذكي لفهم السوق والمنافسين وتحليل البراندات.',
    category: 'تسويق',
    toolUrl: 'https://ubersuggest.com/',
    imageUrl: 'https://picsum.photos/seed/Ubersuggest/500/300',
    featured: false,
  },
  {
    id: 'tool-62',
    name: 'Pomelli',
    description: 'يحلل موقعك ويصنع DNA خاص بعلامتك التجارية (نغمة، خطوط، ألوان).',
    category: 'تسويق',
    toolUrl: 'https://labs.google.com/pomelli/about/',
    imageUrl: 'https://picsum.photos/seed/Pomelli/500/300',
    featured: false,
  },
  {
    id: 'tool-63',
    name: 'Crystal Knows',
    description: 'منصة AI لتحليل الشخصية لفرق المبيعات.',
    category: 'تسويق',
    toolUrl: 'https://www.crystalknows.com/',
    imageUrl: 'https://picsum.photos/seed/Crystal Knows/500/300',
    featured: false,
  },
  {
    id: 'tool-64',
    name: 'Supergrow',
    description: 'أداة لتنمية الحسابات على لينكدإن باستخدام AI.',
    category: 'تسويق',
    toolUrl: 'https://www.supergrow.ai/',
    imageUrl: 'https://picsum.photos/seed/Supergrow/500/300',
    featured: false,
  },
  {
    id: 'tool-65',
    name: 'Happenstance',
    description: 'أداة لإنشاء رسائل فيديو مخصصة للمبيعات.',
    category: 'تسويق',
    toolUrl: 'https://www.happenstance.com/',
    imageUrl: 'https://picsum.photos/seed/Happenstance/500/300',
    featured: false,
  },
  {
    id: 'tool-66',
    name: 'Flick',
    description: 'أداة لإدارة وجدولة المحتوى على وسائل التواصل الاجتماعي.',
    category: 'تسويق',
    toolUrl: 'https://www.theflick.app/',
    imageUrl: 'https://picsum.photos/seed/Flick/500/300',
    featured: false,
  },
  {
    id: 'tool-67',
    name: 'Loveable',
    description: 'أداة AI لتوليد رسائل بريد إلكتروني للمبيعات.',
    category: 'تسويق',
    toolUrl: 'https://loveable.ai/',
    imageUrl: 'https://picsum.photos/seed/Loveable/500/300',
    featured: false,
  },
  {
    id: 'tool-68',
    name: 'Higgsfield',
    description: 'منصة لتوليد الميديا والفيديوهات بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://higgsfield.ai/',
    imageUrl: 'https://picsum.photos/seed/Higgsfield/500/300',
    featured: false,
  },
  {
    id: 'tool-69',
    name: '1Resume',
    description: 'صانع سيرة ذاتية (CV) مميز جدا باستخدام الذكاء الاصطناعي.',
    category: 'إنتاجية',
    toolUrl: 'https://1resume.app/',
    imageUrl: 'https://picsum.photos/seed/1Resume/500/300',
    featured: false,
  },
  {
    id: 'tool-70',
    name: 'Granola',
    description: 'مساعد AI لتدوين الملاحظات وتلخيص الاجتماعات.',
    category: 'إنتاجية',
    toolUrl: 'https://granola.ai/',
    imageUrl: 'https://picsum.photos/seed/Granola/500/300',
    featured: false,
  },
  {
    id: 'tool-71',
    name: 'Fireflies',
    description: 'مساعد اجتماعات AI يقوم بنسخ وتلخيص المحادثات.',
    category: 'إنتاجية',
    toolUrl: 'https://fireflies.ai/',
    imageUrl: 'https://picsum.photos/seed/Fireflies/500/300',
    featured: true,
  },
  {
    id: 'tool-72',
    name: 'Otter.ai',
    description: 'أداة لنسخ وتلخيص الاجتماعات والمحادثات الصوتية.',
    category: 'إنتاجية',
    toolUrl: 'https://otter.ai/',
    imageUrl: 'https://picsum.photos/seed/Otter.ai/500/300',
    featured: false,
  },
  {
    id: 'tool-73',
    name: 'Notebook LM',
    description: 'أداة من جوجل لتدوين الملاحظات والبحث في مستنداتك الخاصة.',
    category: 'إنتاجية',
    toolUrl: 'https://notebooklm.google.com/',
    imageUrl: 'https://picsum.photos/seed/Notebook LM/500/300',
    featured: false,
  },
  {
    id: 'tool-74',
    name: 'Numerous AI',
    description: 'مساعد ذكاء اصطناعي لجداول البيانات (Excel/Sheets).',
    category: 'إنتاجية',
    toolUrl: 'https://numerous.ai/',
    imageUrl: 'https://picsum.photos/seed/Numerous AI/500/300',
    featured: false,
  },
  {
    id: 'tool-75',
    name: 'VisualGPT',
    description: 'لتعديل الصور بالذكاء الاصطناعي مجانًا.',
    category: 'ميديا',
    toolUrl: 'https://visualgpt.io/',
    imageUrl: 'https://picsum.photos/seed/VisualGPT/500/300',
    featured: false,
  },
  {
    id: 'tool-76',
    name: 'Qwen3-VL Demo',
    description: 'نموذج لوصف برومبت مثالي للصور والفيديوهات.',
    category: 'ميديا',
    toolUrl: 'https://huggingface.co/spaces/Qwen/Qwen3-VL-30B-A3B-Demo',
    imageUrl: 'https://picsum.photos/seed/Qwen3-VL Demo/500/300',
    featured: false,
  },
  {
    id: 'tool-77',
    name: 'GeminiGen Video',
    description: 'منصة لتوليد الفيديوهات بالذكاء الاصطناعي.',
    category: 'ميديا',
    toolUrl: 'https://geminigen.ai/app/video-gen/',
    imageUrl: 'https://picsum.photos/seed/GeminiGen Video/500/300',
    featured: false,
  },
  {
    id: 'tool-78',
    name: 'مولد الستوري بورد والتحريك',
    description: 'لتوليد ال storyboard للفيديوهات وبرومبات للتحريك.',
    category: 'ميديا',
    toolUrl: 'https://ai.studio/apps/drive/1aEH6f7J2TXUx-GWiZsJp6QPHQ95ykst8',
    imageUrl: 'https://picsum.photos/seed/مولد الستوري بورد والتحريك/500/300',
    featured: false,
  },
  {
    id: 'tool-79',
    name: 'replit',
    description: 'No description available.',
    category: 'vibe coding',
    toolUrl: 'https://replit.com/~',
    imageUrl: 'https://picsum.photos/seed/replit/500/300',
    featured: true,
  },
  {
    id: 'tool-80',
    name: 'lyzr',
    description: 'No description available.',
    category: 'وكلاء',
    toolUrl: 'https://studio.lyzr.ai/agent-builder',
    imageUrl: 'https://picsum.photos/seed/lyzr/500/300',
    featured: false,
  },
  {
    id: 'tool-81',
    name: 'ollama',
    description: 'No description available.',
    category: 'محادثة',
    toolUrl: 'https://ollama.com/',
    imageUrl: 'https://picsum.photos/seed/ollama/500/300',
    featured: false,
  },
  {
    id: 'tool-82',
    name: 'openrouter ai',
    description: 'No description available.',
    category: 'محادثة',
    toolUrl: 'https://openrouter.ai/c',
    imageUrl: 'https://picsum.photos/seed/openrouter ai/500/300',
    featured: false,
  },
  {
    id: 'tool-83',
    name: 'gofullpage',
    description: 'No description available.',
    category: 'اضافة متصفح',
    toolUrl: 'https://gofullpage.com/',
    imageUrl: 'https://picsum.photos/seed/gofullpage/500/300',
    featured: false,
  },
];
